// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/layout/Aside.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb.vue')['default']
    CountDownUp: typeof import('./src/components/CountDownUp.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Empty: typeof import('./src/components/Empty.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    Main: typeof import('./src/components/layout/Main.vue')['default']
    MapChoose: typeof import('./src/components/MapChoose.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Table: typeof import('./src/components/Table/index.vue')['default']
    TableColumn: typeof import('./src/components/Table/components/TableColumn.vue')['default']
    TableForm: typeof import('./src/components/Table/components/TableForm.vue')['default']
    UploadImg: typeof import('./src/components/UploadImg.vue')['default']
  }
}
